#ifndef CTLARK__LARK__HPP
#define CTLARK__LARK__HPP

// THIS FILE WAS GENERATED BY TABLEWRIGHT TOOL, DO NOT MODIFY THIS FILE

#include "../ctll/grammars.hpp"

namespace ctlark {

struct lark_grammar {

	// NONTERMINALS:
	struct after_alias {};
	struct after_rule_ref {};
	struct after_term_ref {};
	struct alias_name {};
	struct alias_tail {};
	struct alias_uscore_run {};
	struct cls_after_char {};
	struct cls_after_range {};
	struct cls_escape {};
	struct cls_first {};
	struct cls_first_pos {};
	struct cls_items {};
	struct cls_range_end {};
	struct cls_range_escape {};
	struct comment_tail {};
	struct exp_after_nl {};
	struct exp_atoms {};
	struct exp_atoms_rep {};
	struct import_alias_lc {};
	struct import_alias_name {};
	struct import_alias_run {};
	struct import_alias_uc {};
	struct import_list_lc {};
	struct import_list_name {};
	struct import_list_post {};
	struct import_list_run {};
	struct import_list_uc {};
	struct import_path {};
	struct import_post {};
	struct import_post2 {};
	struct import_seg_lc {};
	struct import_seg_run {};
	struct import_seg_uc {};
	struct item {};
	struct item_after_bang {};
	struct item_rule_name {};
	struct item_uscore_rule {};
	struct item_uscore_run {};
	struct items {};
	struct lark_file {}; using _start = lark_file;
	struct line_end {};
	struct number {};
	struct number_tail {};
	struct range_second {};
	struct range_string_body {};
	struct range_string_escape {};
	struct ref_uscore_run {};
	struct regex_or_comment {};
	struct rule_def_post {};
	struct rule_def_post2 {};
	struct rule_name_tail {};
	struct rule_ref_tail {};
	struct rx_atoms {};
	struct rx_brace {};
	struct rx_brace2 {};
	struct rx_class_open {};
	struct rx_escape {};
	struct rx_first {};
	struct rx_flags {};
	struct rx_group_first {};
	struct rx_group_open {};
	struct skip {};
	struct statement {};
	struct statement_i {};
	struct string_body {};
	struct string_escape {};
	struct string_post {};
	struct string_post_i {};
	struct term_def_post {};
	struct term_def_post2 {};
	struct term_name_tail {};
	struct term_ref_tail {};
	struct ws {};
	struct ws1 {};

	// 'action' types:
	struct attach_alias: ctll::action {};
	struct begin_name: ctll::action {};
	struct begin_number: ctll::action {};
	struct begin_string: ctll::action {};
	struct branch: ctll::action {};
	struct close_class: ctll::action {};
	struct close_group: ctll::action {};
	struct close_maybe: ctll::action {};
	struct close_regex: ctll::action {};
	struct cls_class_digit: ctll::action {};
	struct cls_class_not_digit: ctll::action {};
	struct cls_class_not_space: ctll::action {};
	struct cls_class_not_word: ctll::action {};
	struct cls_class_space: ctll::action {};
	struct cls_class_word: ctll::action {};
	struct cls_esc_char: ctll::action {};
	struct cls_esc_code: ctll::action {};
	struct cls_hex_char: ctll::action {};
	struct cls_make_range: ctll::action {};
	struct cls_push_char: ctll::action {};
	struct cls_push_minus: ctll::action {};
	struct cls_push_rbracket: ctll::action {};
	struct cls_range_esc_char: ctll::action {};
	struct cls_range_esc_code: ctll::action {};
	struct cls_range_hex_char: ctll::action {};
	struct def_rule: ctll::action {};
	struct def_term: ctll::action {};
	struct end_item: ctll::action {};
	struct end_string: ctll::action {};
	struct import_alias: ctll::action {};
	struct import_list_add: ctll::action {};
	struct import_seg: ctll::action {};
	struct make_char_range: ctll::action {};
	struct make_opt: ctll::action {};
	struct make_plus: ctll::action {};
	struct make_rep_exact: ctll::action {};
	struct make_rep_open: ctll::action {};
	struct make_rep_range: ctll::action {};
	struct make_rule_ref: ctll::action {};
	struct make_star: ctll::action {};
	struct make_term_ref: ctll::action {};
	struct mark_bang: ctll::action {};
	struct mark_ci: ctll::action {};
	struct mark_class_neg: ctll::action {};
	struct mark_cond: ctll::action {};
	struct mark_ignore: ctll::action {};
	struct mark_import: ctll::action {};
	struct negate_number: ctll::action {};
	struct new_branch: ctll::action {};
	struct open_class: ctll::action {};
	struct open_group: ctll::action {};
	struct open_maybe: ctll::action {};
	struct open_regex: ctll::action {};
	struct push_esc_char: ctll::action {};
	struct push_esc_code: ctll::action {};
	struct push_hex_high: ctll::action {};
	struct push_hex_low: ctll::action {};
	struct push_name_char: ctll::action {};
	struct push_number_digit: ctll::action {};
	struct push_str_char: ctll::action {};
	struct rx_class_digit: ctll::action {};
	struct rx_class_not_digit: ctll::action {};
	struct rx_class_not_space: ctll::action {};
	struct rx_class_not_word: ctll::action {};
	struct rx_class_space: ctll::action {};
	struct rx_class_word: ctll::action {};
	struct rx_dot: ctll::action {};
	struct rx_esc_code: ctll::action {};
	struct rx_flag_ci: ctll::action {};
	struct rx_flag_dotall: ctll::action {};
	struct rx_hex_char: ctll::action {};
	struct rx_push_char: ctll::action {};

	// TERMINALS
	using set_1 = ctll::set<'\x09','\x0A','\x0D',' ','!','%','/','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using set_2 = ctll::set<'!','%','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using slash = ctll::term<'/'>;
	using inline_ws__x0a = ctll::set<'\x09','\x0A','\x0D',' '>;
	using set_3 = ctll::set<'!','%','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','|'>;
	using comment_char = ctll::neg_set<'\x0A'>;
	using newline = ctll::term<'\x0A'>;
	using excl = ctll::term<'!'>;
	using quest = ctll::term<'?'>;
	using uscore = ctll::term<'_'>;
	using set_4 = ctll::set<'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using set_5 = ctll::set<'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'>;
	using percent = ctll::term<'%'>;
	using set_6 = ctll::set<'_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using set_7 = ctll::set<'0','1','2','3','4','5','6','7','8','9','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using inline_ws__dot__colon = ctll::set<'\x09','\x0D',' ','.',':'>;
	using set_8 = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_'>;
	using inline_ws = ctll::set<'\x09','\x0D',' '>;
	using dot = ctll::term<'.'>;
	using colon = ctll::term<':'>;
	using digit = ctll::set<'0','1','2','3','4','5','6','7','8','9'>;
	using minus = ctll::term<'-'>;
	using set_9 = ctll::set<'\x09','\x0A','\x0D',' ','!','\"','%','\x28','\x29','*','+',',','-','.','/',':','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[',']','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','|','\x7D','~'>;
	using set_10 = ctll::set<'\x0A','!','\"','%','\x28','\x29','*','+','-','/','0','1','2','3','4','5','6','7','8','9','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[',']','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','|','\x7D','~'>;
	using gt = ctll::term<'>'>;
	using pipe = ctll::term<'|'>;
	using star = ctll::term<'*'>;
	using plus = ctll::term<'+'>;
	using tilde = ctll::term<'~'>;
	using lparen = ctll::term<'\x28'>;
	using rparen = ctll::term<'\x29'>;
	using lbracket = ctll::term<'['>;
	using rbracket = ctll::term<']'>;
	using quote = ctll::term<'\"'>;
	using exclamation_mark__percent = ctll::set<'!','%'>;
	using set_11 = ctll::set<'\x09','\x0A','\x0D',' ','!','\"','%','\x28','\x29','*','+','-','/','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[',']','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','|','~'>;
	using set_12 = ctll::set<'\x09','\x0A','\x0D',' ','!','%','/','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','|'>;
	using set_13 = ctll::set<'\x09','\x0A','\x0D',' ','!','\"','%','\x28','\x29','*','+','-','/','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[',']','|','~'>;
	using set_14 = ctll::set<'\x09','\x0A','\x0D',' ','!','\"','%','\x28','\x29','*','+','-','/','?','[',']','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','|','~'>;
	using set_15 = ctll::set<'!','%','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using set_16 = ctll::set<'!','%','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_'>;
	using str_char = ctll::neg_set<'\x0A','\"','\\'>;
	using backslash = ctll::term<'\\'>;
	using hexdig = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','a','b','c','d','e','f'>;
	using f__n__r__t = ctll::set<'f','n','r','t'>;
	using doublequote__quote__slash__backslash = ctll::set<'\"','\'','/','\\'>;
	using x = ctll::term<'x'>;
	using i = ctll::term<'i'>;
	using set_17 = ctll::set<'a','b','c','d','e','f','g','h','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using open__dot__sopen__backslash__pipe = ctll::set<'\x28','.','[','\\','|'>;
	using rx_char = ctll::neg_set<'\x0A','$','\x28','\x29','*','+','.','/','?','[','\\',']','^','\x7B','|','\x7D'>;
	using lbrace = ctll::term<'\x7B'>;
	using set_18 = ctll::set<'\x28','\x29','*','+','.','/','[','\\','\x7B','|'>;
	using rbrace = ctll::term<'\x7D'>;
	using comma = ctll::term<','>;
	using w = ctll::term<'w'>;
	using d = ctll::term<'d'>;
	using s = ctll::term<'s'>;
	using W = ctll::term<'W'>;
	using D = ctll::term<'D'>;
	using S = ctll::term<'S'>;
	using set_19 = ctll::set<'$','\x28','\x29','*','+',',','-','.','/','?','[','\\',']','^','\x7B','|','\x7D'>;
	using l__m__u = ctll::set<'l','m','u'>;
	using set_20 = ctll::set<'a','b','c','d','e','f','g','h','j','k','n','o','p','q','r','t','v','w','x','y','z'>;
	using caret = ctll::term<'^'>;
	using minus__backslash__sclose = ctll::set<'-','\\',']'>;
	using cls_char = ctll::neg_set<'\x0A','-','\\',']','^'>;
	using minus__caret = ctll::set<'-','^'>;
	using backslash__sclose__caret = ctll::set<'\\',']','^'>;
	using set_21 = ctll::set<'$','*','+','-','.','/','?','[','\\',']','^'>;
	using minus__sopen__backslash__sclose__caret = ctll::set<'-','[','\\',']','^'>;
	using n = ctll::term<'n'>;
	using o = ctll::term<'o'>;
	using r = ctll::term<'r'>;
	using e = ctll::term<'e'>;
	using p = ctll::term<'p'>;
	using t = ctll::term<'t'>;
	using g = ctll::term<'g'>;
	using m = ctll::term<'m'>;
	using set_22 = ctll::set<'\x09','\x0A','\x0D',' ','!','%','.','/','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'>;
	using set_23 = ctll::set<'\x09','\x0A','\x0D',' ','!','%','.','/','?','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using set_24 = ctll::set<'\x09','\x0A','\x0D',' ','!','%','/','?','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z'>;
	using set_25 = ctll::set<'\x09','\x0A','\x0D',' ','!','%','/','?','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using inline_ws__close__comma = ctll::set<'\x09','\x0D',' ','\x29',','>;

	// (q)LL1 function:
	static constexpr auto rule(lark_file, set_1) -> ctll::push<skip, items>;
	static constexpr auto rule(lark_file, ctll::epsilon) -> ctll::push<skip, items>;

	static constexpr auto rule(items, set_2) -> ctll::push<item, end_item, items>;
	static constexpr auto rule(items, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(skip, inline_ws__x0a) -> ctll::push<ctll::anything, skip>;
	static constexpr auto rule(skip, slash) -> ctll::push<ctll::anything, slash, comment_tail>;
	static constexpr auto rule(skip, set_3) -> ctll::epsilon;
	static constexpr auto rule(skip, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(comment_tail, comment_char) -> ctll::push<ctll::anything, comment_tail>;
	static constexpr auto rule(comment_tail, newline) -> ctll::push<ctll::anything, skip>;
	static constexpr auto rule(comment_tail, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(item, excl) -> ctll::push<ctll::anything, mark_bang, item_after_bang>;
	static constexpr auto rule(item, quest) -> ctll::push<ctll::anything, mark_cond, item_rule_name>;
	static constexpr auto rule(item, uscore) -> ctll::push<ctll::anything, begin_name, push_name_char, item_uscore_run>;
	static constexpr auto rule(item, set_4) -> ctll::push<ctll::anything, begin_name, push_name_char, rule_name_tail>;
	static constexpr auto rule(item, set_5) -> ctll::push<ctll::anything, begin_name, push_name_char, term_name_tail>;
	static constexpr auto rule(item, percent) -> ctll::push<ctll::anything, statement>;

	static constexpr auto rule(item_after_bang, quest) -> ctll::push<ctll::anything, mark_cond, item_rule_name>;
	static constexpr auto rule(item_after_bang, set_6) -> ctll::push<item_rule_name>;

	static constexpr auto rule(item_rule_name, uscore) -> ctll::push<ctll::anything, begin_name, push_name_char, item_uscore_rule>;
	static constexpr auto rule(item_rule_name, set_4) -> ctll::push<ctll::anything, begin_name, push_name_char, rule_name_tail>;

	static constexpr auto rule(item_uscore_rule, uscore) -> ctll::push<ctll::anything, push_name_char, item_uscore_rule>;
	static constexpr auto rule(item_uscore_rule, set_4) -> ctll::push<ctll::anything, push_name_char, rule_name_tail>;

	static constexpr auto rule(item_uscore_run, uscore) -> ctll::push<ctll::anything, push_name_char, item_uscore_run>;
	static constexpr auto rule(item_uscore_run, set_4) -> ctll::push<ctll::anything, push_name_char, rule_name_tail>;
	static constexpr auto rule(item_uscore_run, set_5) -> ctll::push<ctll::anything, push_name_char, term_name_tail>;

	static constexpr auto rule(rule_name_tail, set_7) -> ctll::push<ctll::anything, push_name_char, rule_name_tail>;
	static constexpr auto rule(rule_name_tail, inline_ws__dot__colon) -> ctll::push<rule_def_post>;

	static constexpr auto rule(term_name_tail, set_8) -> ctll::push<ctll::anything, push_name_char, term_name_tail>;
	static constexpr auto rule(term_name_tail, inline_ws__dot__colon) -> ctll::push<term_def_post>;

	static constexpr auto rule(rule_def_post, inline_ws) -> ctll::push<ctll::anything, rule_def_post>;
	static constexpr auto rule(rule_def_post, dot) -> ctll::push<ctll::anything, number, rule_def_post2>;
	static constexpr auto rule(rule_def_post, colon) -> ctll::push<ctll::anything, def_rule, ws, exp_atoms>;

	static constexpr auto rule(rule_def_post2, inline_ws) -> ctll::push<ctll::anything, rule_def_post2>;
	static constexpr auto rule(rule_def_post2, colon) -> ctll::push<ctll::anything, def_rule, ws, exp_atoms>;

	static constexpr auto rule(term_def_post, inline_ws) -> ctll::push<ctll::anything, term_def_post>;
	static constexpr auto rule(term_def_post, dot) -> ctll::push<ctll::anything, number, term_def_post2>;
	static constexpr auto rule(term_def_post, colon) -> ctll::push<ctll::anything, def_term, ws, exp_atoms>;

	static constexpr auto rule(term_def_post2, inline_ws) -> ctll::push<ctll::anything, term_def_post2>;
	static constexpr auto rule(term_def_post2, colon) -> ctll::push<ctll::anything, def_term, ws, exp_atoms>;

	static constexpr auto rule(number, minus) -> ctll::push<ctll::anything, begin_number, negate_number, digit, push_number_digit, number_tail>;
	static constexpr auto rule(number, digit) -> ctll::push<ctll::anything, begin_number, push_number_digit, number_tail>;

	static constexpr auto rule(number_tail, digit) -> ctll::push<ctll::anything, push_number_digit, number_tail>;
	static constexpr auto rule(number_tail, set_9) -> ctll::epsilon;
	static constexpr auto rule(number_tail, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(ws, inline_ws) -> ctll::push<ctll::anything, ws>;
	static constexpr auto rule(ws, set_10) -> ctll::epsilon;
	static constexpr auto rule(ws, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(exp_atoms, inline_ws) -> ctll::push<ctll::anything, exp_atoms>;
	static constexpr auto rule(exp_atoms, pipe) -> ctll::push<ctll::anything, branch, new_branch, exp_atoms>;
	static constexpr auto rule(exp_atoms, star) -> ctll::push<ctll::anything, make_star, exp_atoms>;
	static constexpr auto rule(exp_atoms, plus) -> ctll::push<ctll::anything, make_plus, exp_atoms>;
	static constexpr auto rule(exp_atoms, quest) -> ctll::push<ctll::anything, make_opt, exp_atoms>;
	static constexpr auto rule(exp_atoms, tilde) -> ctll::push<ctll::anything, ws, number, exp_atoms_rep>;
	static constexpr auto rule(exp_atoms, minus) -> ctll::push<ctll::anything, gt, branch, ws, alias_name>;
	static constexpr auto rule(exp_atoms, lparen) -> ctll::push<ctll::anything, open_group, new_branch, exp_atoms>;
	static constexpr auto rule(exp_atoms, rparen) -> ctll::push<ctll::anything, close_group, exp_atoms>;
	static constexpr auto rule(exp_atoms, lbracket) -> ctll::push<ctll::anything, open_maybe, new_branch, exp_atoms>;
	static constexpr auto rule(exp_atoms, rbracket) -> ctll::push<ctll::anything, close_maybe, exp_atoms>;
	static constexpr auto rule(exp_atoms, uscore) -> ctll::push<ctll::anything, begin_name, push_name_char, ref_uscore_run>;
	static constexpr auto rule(exp_atoms, set_4) -> ctll::push<ctll::anything, begin_name, push_name_char, rule_ref_tail>;
	static constexpr auto rule(exp_atoms, set_5) -> ctll::push<ctll::anything, begin_name, push_name_char, term_ref_tail>;
	static constexpr auto rule(exp_atoms, quote) -> ctll::push<ctll::anything, begin_string, string_body>;
	static constexpr auto rule(exp_atoms, slash) -> ctll::push<ctll::anything, regex_or_comment>;
	static constexpr auto rule(exp_atoms, newline) -> ctll::push<ctll::anything, branch, skip, exp_after_nl>;
	static constexpr auto rule(exp_atoms, exclamation_mark__percent) -> ctll::epsilon;
	static constexpr auto rule(exp_atoms, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(exp_atoms_rep, dot) -> ctll::push<ctll::anything, dot, ws, number, make_rep_range, exp_atoms>;
	static constexpr auto rule(exp_atoms_rep, set_11) -> ctll::push<exp_atoms>;
	static constexpr auto rule(exp_atoms_rep, ctll::epsilon) -> ctll::push<exp_atoms>;

	static constexpr auto rule(exp_after_nl, pipe) -> ctll::push<ctll::anything, new_branch, ws, exp_atoms>;
	static constexpr auto rule(exp_after_nl, set_2) -> ctll::epsilon;
	static constexpr auto rule(exp_after_nl, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(alias_name, uscore) -> ctll::push<ctll::anything, begin_name, push_name_char, alias_uscore_run>;
	static constexpr auto rule(alias_name, set_4) -> ctll::push<ctll::anything, begin_name, push_name_char, alias_tail>;

	static constexpr auto rule(alias_uscore_run, uscore) -> ctll::push<ctll::anything, push_name_char, alias_uscore_run>;
	static constexpr auto rule(alias_uscore_run, set_4) -> ctll::push<ctll::anything, push_name_char, alias_tail>;

	static constexpr auto rule(alias_tail, set_7) -> ctll::push<ctll::anything, push_name_char, alias_tail>;
	static constexpr auto rule(alias_tail, set_12) -> ctll::push<attach_alias, after_alias>;
	static constexpr auto rule(alias_tail, ctll::epsilon) -> ctll::push<attach_alias, after_alias>;

	static constexpr auto rule(after_alias, inline_ws) -> ctll::push<ctll::anything, after_alias>;
	static constexpr auto rule(after_alias, pipe) -> ctll::push<ctll::anything, new_branch, ws, exp_atoms>;
	static constexpr auto rule(after_alias, newline) -> ctll::push<ctll::anything, skip, exp_after_nl>;
	static constexpr auto rule(after_alias, slash) -> ctll::push<ctll::anything, slash, comment_tail, exp_after_nl>;
	static constexpr auto rule(after_alias, set_2) -> ctll::epsilon;
	static constexpr auto rule(after_alias, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(ref_uscore_run, uscore) -> ctll::push<ctll::anything, push_name_char, ref_uscore_run>;
	static constexpr auto rule(ref_uscore_run, set_4) -> ctll::push<ctll::anything, push_name_char, rule_ref_tail>;
	static constexpr auto rule(ref_uscore_run, set_5) -> ctll::push<ctll::anything, push_name_char, term_ref_tail>;

	static constexpr auto rule(rule_ref_tail, set_7) -> ctll::push<ctll::anything, push_name_char, rule_ref_tail>;
	static constexpr auto rule(rule_ref_tail, set_13) -> ctll::push<make_rule_ref, after_rule_ref>;
	static constexpr auto rule(rule_ref_tail, ctll::epsilon) -> ctll::push<make_rule_ref, after_rule_ref>;

	static constexpr auto rule(term_ref_tail, set_8) -> ctll::push<ctll::anything, push_name_char, term_ref_tail>;
	static constexpr auto rule(term_ref_tail, set_14) -> ctll::push<make_term_ref, after_term_ref>;
	static constexpr auto rule(term_ref_tail, ctll::epsilon) -> ctll::push<make_term_ref, after_term_ref>;

	static constexpr auto rule(after_rule_ref, inline_ws) -> ctll::push<ctll::anything, exp_atoms>;
	static constexpr auto rule(after_rule_ref, pipe) -> ctll::push<ctll::anything, branch, new_branch, exp_atoms>;
	static constexpr auto rule(after_rule_ref, star) -> ctll::push<ctll::anything, make_star, exp_atoms>;
	static constexpr auto rule(after_rule_ref, plus) -> ctll::push<ctll::anything, make_plus, exp_atoms>;
	static constexpr auto rule(after_rule_ref, quest) -> ctll::push<ctll::anything, make_opt, exp_atoms>;
	static constexpr auto rule(after_rule_ref, tilde) -> ctll::push<ctll::anything, ws, number, exp_atoms_rep>;
	static constexpr auto rule(after_rule_ref, minus) -> ctll::push<ctll::anything, gt, branch, ws, alias_name>;
	static constexpr auto rule(after_rule_ref, lparen) -> ctll::push<ctll::anything, open_group, new_branch, exp_atoms>;
	static constexpr auto rule(after_rule_ref, rparen) -> ctll::push<ctll::anything, close_group, exp_atoms>;
	static constexpr auto rule(after_rule_ref, lbracket) -> ctll::push<ctll::anything, open_maybe, new_branch, exp_atoms>;
	static constexpr auto rule(after_rule_ref, rbracket) -> ctll::push<ctll::anything, close_maybe, exp_atoms>;
	static constexpr auto rule(after_rule_ref, set_5) -> ctll::push<ctll::anything, begin_name, push_name_char, term_ref_tail>;
	static constexpr auto rule(after_rule_ref, quote) -> ctll::push<ctll::anything, begin_string, string_body>;
	static constexpr auto rule(after_rule_ref, slash) -> ctll::push<ctll::anything, regex_or_comment>;
	static constexpr auto rule(after_rule_ref, newline) -> ctll::push<ctll::anything, branch, skip, exp_after_nl>;
	static constexpr auto rule(after_rule_ref, set_15) -> ctll::epsilon;
	static constexpr auto rule(after_rule_ref, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(after_term_ref, inline_ws) -> ctll::push<ctll::anything, exp_atoms>;
	static constexpr auto rule(after_term_ref, pipe) -> ctll::push<ctll::anything, branch, new_branch, exp_atoms>;
	static constexpr auto rule(after_term_ref, star) -> ctll::push<ctll::anything, make_star, exp_atoms>;
	static constexpr auto rule(after_term_ref, plus) -> ctll::push<ctll::anything, make_plus, exp_atoms>;
	static constexpr auto rule(after_term_ref, quest) -> ctll::push<ctll::anything, make_opt, exp_atoms>;
	static constexpr auto rule(after_term_ref, tilde) -> ctll::push<ctll::anything, ws, number, exp_atoms_rep>;
	static constexpr auto rule(after_term_ref, minus) -> ctll::push<ctll::anything, gt, branch, ws, alias_name>;
	static constexpr auto rule(after_term_ref, lparen) -> ctll::push<ctll::anything, open_group, new_branch, exp_atoms>;
	static constexpr auto rule(after_term_ref, rparen) -> ctll::push<ctll::anything, close_group, exp_atoms>;
	static constexpr auto rule(after_term_ref, lbracket) -> ctll::push<ctll::anything, open_maybe, new_branch, exp_atoms>;
	static constexpr auto rule(after_term_ref, rbracket) -> ctll::push<ctll::anything, close_maybe, exp_atoms>;
	static constexpr auto rule(after_term_ref, set_4) -> ctll::push<ctll::anything, begin_name, push_name_char, rule_ref_tail>;
	static constexpr auto rule(after_term_ref, quote) -> ctll::push<ctll::anything, begin_string, string_body>;
	static constexpr auto rule(after_term_ref, slash) -> ctll::push<ctll::anything, regex_or_comment>;
	static constexpr auto rule(after_term_ref, newline) -> ctll::push<ctll::anything, branch, skip, exp_after_nl>;
	static constexpr auto rule(after_term_ref, set_16) -> ctll::epsilon;
	static constexpr auto rule(after_term_ref, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(string_body, str_char) -> ctll::push<ctll::anything, push_str_char, string_body>;
	static constexpr auto rule(string_body, backslash) -> ctll::push<ctll::anything, string_escape>;
	static constexpr auto rule(string_body, quote) -> ctll::push<ctll::anything, end_string, string_post>;

	static constexpr auto rule(string_escape, f__n__r__t) -> ctll::push<ctll::anything, push_esc_code, string_body>;
	static constexpr auto rule(string_escape, doublequote__quote__slash__backslash) -> ctll::push<ctll::anything, push_esc_char, string_body>;
	static constexpr auto rule(string_escape, x) -> ctll::push<ctll::anything, hexdig, push_hex_high, hexdig, push_hex_low, string_body>;

	static constexpr auto rule(string_post, i) -> ctll::push<ctll::anything, mark_ci, string_post_i>;
	static constexpr auto rule(string_post, dot) -> ctll::push<ctll::anything, dot, ws, range_second>;
	static constexpr auto rule(string_post, uscore) -> ctll::push<ctll::anything, begin_name, push_name_char, ref_uscore_run>;
	static constexpr auto rule(string_post, set_17) -> ctll::push<ctll::anything, begin_name, push_name_char, rule_ref_tail>;
	static constexpr auto rule(string_post, set_5) -> ctll::push<ctll::anything, begin_name, push_name_char, term_ref_tail>;
	static constexpr auto rule(string_post, inline_ws) -> ctll::push<ctll::anything, exp_atoms>;
	static constexpr auto rule(string_post, pipe) -> ctll::push<ctll::anything, branch, new_branch, exp_atoms>;
	static constexpr auto rule(string_post, star) -> ctll::push<ctll::anything, make_star, exp_atoms>;
	static constexpr auto rule(string_post, plus) -> ctll::push<ctll::anything, make_plus, exp_atoms>;
	static constexpr auto rule(string_post, quest) -> ctll::push<ctll::anything, make_opt, exp_atoms>;
	static constexpr auto rule(string_post, tilde) -> ctll::push<ctll::anything, ws, number, exp_atoms_rep>;
	static constexpr auto rule(string_post, minus) -> ctll::push<ctll::anything, gt, branch, ws, alias_name>;
	static constexpr auto rule(string_post, lparen) -> ctll::push<ctll::anything, open_group, new_branch, exp_atoms>;
	static constexpr auto rule(string_post, rparen) -> ctll::push<ctll::anything, close_group, exp_atoms>;
	static constexpr auto rule(string_post, lbracket) -> ctll::push<ctll::anything, open_maybe, new_branch, exp_atoms>;
	static constexpr auto rule(string_post, rbracket) -> ctll::push<ctll::anything, close_maybe, exp_atoms>;
	static constexpr auto rule(string_post, quote) -> ctll::push<ctll::anything, begin_string, string_body>;
	static constexpr auto rule(string_post, slash) -> ctll::push<ctll::anything, regex_or_comment>;
	static constexpr auto rule(string_post, newline) -> ctll::push<ctll::anything, branch, skip, exp_after_nl>;
	static constexpr auto rule(string_post, exclamation_mark__percent) -> ctll::epsilon;
	static constexpr auto rule(string_post, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(string_post_i, dot) -> ctll::push<ctll::anything, dot, ws, range_second>;
	static constexpr auto rule(string_post_i, set_11) -> ctll::push<exp_atoms>;
	static constexpr auto rule(string_post_i, ctll::epsilon) -> ctll::push<exp_atoms>;

	static constexpr auto rule(range_second, quote) -> ctll::push<ctll::anything, begin_string, range_string_body>;

	static constexpr auto rule(range_string_body, str_char) -> ctll::push<ctll::anything, push_str_char, range_string_body>;
	static constexpr auto rule(range_string_body, backslash) -> ctll::push<ctll::anything, range_string_escape>;
	static constexpr auto rule(range_string_body, quote) -> ctll::push<ctll::anything, end_string, make_char_range, exp_atoms>;

	static constexpr auto rule(range_string_escape, f__n__r__t) -> ctll::push<ctll::anything, push_esc_code, range_string_body>;
	static constexpr auto rule(range_string_escape, doublequote__quote__slash__backslash) -> ctll::push<ctll::anything, push_esc_char, range_string_body>;
	static constexpr auto rule(range_string_escape, x) -> ctll::push<ctll::anything, hexdig, push_hex_high, hexdig, push_hex_low, range_string_body>;

	static constexpr auto rule(regex_or_comment, slash) -> ctll::push<ctll::anything, branch, comment_tail, exp_after_nl>;
	static constexpr auto rule(regex_or_comment, open__dot__sopen__backslash__pipe) -> ctll::push<open_regex, new_branch, rx_first>;
	static constexpr auto rule(regex_or_comment, rx_char) -> ctll::push<open_regex, new_branch, rx_first>;

	static constexpr auto rule(rx_first, rx_char) -> ctll::push<ctll::anything, rx_push_char, rx_atoms>;
	static constexpr auto rule(rx_first, dot) -> ctll::push<ctll::anything, rx_dot, rx_atoms>;
	static constexpr auto rule(rx_first, pipe) -> ctll::push<ctll::anything, branch, new_branch, rx_atoms>;
	static constexpr auto rule(rx_first, lparen) -> ctll::push<ctll::anything, rx_group_open>;
	static constexpr auto rule(rx_first, lbracket) -> ctll::push<ctll::anything, rx_class_open>;
	static constexpr auto rule(rx_first, backslash) -> ctll::push<ctll::anything, rx_escape>;

	static constexpr auto rule(rx_atoms, rx_char) -> ctll::push<ctll::anything, rx_push_char, rx_atoms>;
	static constexpr auto rule(rx_atoms, dot) -> ctll::push<ctll::anything, rx_dot, rx_atoms>;
	static constexpr auto rule(rx_atoms, pipe) -> ctll::push<ctll::anything, branch, new_branch, rx_atoms>;
	static constexpr auto rule(rx_atoms, star) -> ctll::push<ctll::anything, make_star, rx_atoms>;
	static constexpr auto rule(rx_atoms, plus) -> ctll::push<ctll::anything, make_plus, rx_atoms>;
	static constexpr auto rule(rx_atoms, quest) -> ctll::push<ctll::anything, make_opt, rx_atoms>;
	static constexpr auto rule(rx_atoms, lparen) -> ctll::push<ctll::anything, rx_group_open>;
	static constexpr auto rule(rx_atoms, rparen) -> ctll::push<ctll::anything, close_group, rx_atoms>;
	static constexpr auto rule(rx_atoms, lbracket) -> ctll::push<ctll::anything, rx_class_open>;
	static constexpr auto rule(rx_atoms, lbrace) -> ctll::push<ctll::anything, ws, number, rx_brace>;
	static constexpr auto rule(rx_atoms, backslash) -> ctll::push<ctll::anything, rx_escape>;
	static constexpr auto rule(rx_atoms, slash) -> ctll::push<ctll::anything, close_regex, rx_flags>;

	static constexpr auto rule(rx_group_open, quest) -> ctll::push<ctll::anything, colon, open_group, new_branch, rx_atoms>;
	static constexpr auto rule(rx_group_open, set_18) -> ctll::push<open_group, new_branch, rx_group_first>;
	static constexpr auto rule(rx_group_open, rx_char) -> ctll::push<open_group, new_branch, rx_group_first>;

	static constexpr auto rule(rx_group_first, rx_char) -> ctll::push<ctll::anything, rx_push_char, rx_atoms>;
	static constexpr auto rule(rx_group_first, dot) -> ctll::push<ctll::anything, rx_dot, rx_atoms>;
	static constexpr auto rule(rx_group_first, pipe) -> ctll::push<ctll::anything, branch, new_branch, rx_atoms>;
	static constexpr auto rule(rx_group_first, star) -> ctll::push<ctll::anything, make_star, rx_atoms>;
	static constexpr auto rule(rx_group_first, plus) -> ctll::push<ctll::anything, make_plus, rx_atoms>;
	static constexpr auto rule(rx_group_first, lparen) -> ctll::push<ctll::anything, rx_group_open>;
	static constexpr auto rule(rx_group_first, rparen) -> ctll::push<ctll::anything, close_group, rx_atoms>;
	static constexpr auto rule(rx_group_first, lbracket) -> ctll::push<ctll::anything, rx_class_open>;
	static constexpr auto rule(rx_group_first, lbrace) -> ctll::push<ctll::anything, ws, number, rx_brace>;
	static constexpr auto rule(rx_group_first, backslash) -> ctll::push<ctll::anything, rx_escape>;
	static constexpr auto rule(rx_group_first, slash) -> ctll::push<ctll::anything, close_regex, rx_flags>;

	static constexpr auto rule(rx_brace, rbrace) -> ctll::push<ctll::anything, make_rep_exact, rx_atoms>;
	static constexpr auto rule(rx_brace, comma) -> ctll::push<ctll::anything, ws, rx_brace2>;

	static constexpr auto rule(rx_brace2, rbrace) -> ctll::push<ctll::anything, make_rep_open, rx_atoms>;
	static constexpr auto rule(rx_brace2, digit) -> ctll::push<ctll::anything, begin_number, push_number_digit, number_tail, rbrace, make_rep_range, rx_atoms>;

	static constexpr auto rule(rx_escape, f__n__r__t) -> ctll::push<ctll::anything, rx_esc_code, rx_atoms>;
	static constexpr auto rule(rx_escape, w) -> ctll::push<ctll::anything, rx_class_word, rx_atoms>;
	static constexpr auto rule(rx_escape, d) -> ctll::push<ctll::anything, rx_class_digit, rx_atoms>;
	static constexpr auto rule(rx_escape, s) -> ctll::push<ctll::anything, rx_class_space, rx_atoms>;
	static constexpr auto rule(rx_escape, W) -> ctll::push<ctll::anything, rx_class_not_word, rx_atoms>;
	static constexpr auto rule(rx_escape, D) -> ctll::push<ctll::anything, rx_class_not_digit, rx_atoms>;
	static constexpr auto rule(rx_escape, S) -> ctll::push<ctll::anything, rx_class_not_space, rx_atoms>;
	static constexpr auto rule(rx_escape, x) -> ctll::push<ctll::anything, hexdig, push_hex_high, hexdig, rx_hex_char, rx_atoms>;
	static constexpr auto rule(rx_escape, set_19) -> ctll::push<ctll::anything, rx_push_char, rx_atoms>;

	static constexpr auto rule(rx_flags, i) -> ctll::push<ctll::anything, rx_flag_ci, rx_flags>;
	static constexpr auto rule(rx_flags, s) -> ctll::push<ctll::anything, rx_flag_dotall, rx_flags>;
	static constexpr auto rule(rx_flags, l__m__u) -> ctll::push<ctll::anything, rx_flags>;
	static constexpr auto rule(rx_flags, uscore) -> ctll::push<ctll::anything, begin_name, push_name_char, ref_uscore_run>;
	static constexpr auto rule(rx_flags, set_20) -> ctll::push<ctll::anything, begin_name, push_name_char, rule_ref_tail>;
	static constexpr auto rule(rx_flags, set_5) -> ctll::push<ctll::anything, begin_name, push_name_char, term_ref_tail>;
	static constexpr auto rule(rx_flags, inline_ws) -> ctll::push<ctll::anything, exp_atoms>;
	static constexpr auto rule(rx_flags, pipe) -> ctll::push<ctll::anything, branch, new_branch, exp_atoms>;
	static constexpr auto rule(rx_flags, star) -> ctll::push<ctll::anything, make_star, exp_atoms>;
	static constexpr auto rule(rx_flags, plus) -> ctll::push<ctll::anything, make_plus, exp_atoms>;
	static constexpr auto rule(rx_flags, quest) -> ctll::push<ctll::anything, make_opt, exp_atoms>;
	static constexpr auto rule(rx_flags, tilde) -> ctll::push<ctll::anything, ws, number, exp_atoms_rep>;
	static constexpr auto rule(rx_flags, minus) -> ctll::push<ctll::anything, gt, branch, ws, alias_name>;
	static constexpr auto rule(rx_flags, lparen) -> ctll::push<ctll::anything, open_group, new_branch, exp_atoms>;
	static constexpr auto rule(rx_flags, rparen) -> ctll::push<ctll::anything, close_group, exp_atoms>;
	static constexpr auto rule(rx_flags, lbracket) -> ctll::push<ctll::anything, open_maybe, new_branch, exp_atoms>;
	static constexpr auto rule(rx_flags, rbracket) -> ctll::push<ctll::anything, close_maybe, exp_atoms>;
	static constexpr auto rule(rx_flags, quote) -> ctll::push<ctll::anything, begin_string, string_body>;
	static constexpr auto rule(rx_flags, slash) -> ctll::push<ctll::anything, regex_or_comment>;
	static constexpr auto rule(rx_flags, newline) -> ctll::push<ctll::anything, branch, skip, exp_after_nl>;
	static constexpr auto rule(rx_flags, exclamation_mark__percent) -> ctll::epsilon;
	static constexpr auto rule(rx_flags, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(rx_class_open, caret) -> ctll::push<ctll::anything, open_class, mark_class_neg, cls_first>;
	static constexpr auto rule(rx_class_open, minus__backslash__sclose) -> ctll::push<open_class, cls_first_pos>;
	static constexpr auto rule(rx_class_open, cls_char) -> ctll::push<open_class, cls_first_pos>;

	static constexpr auto rule(cls_first, rbracket) -> ctll::push<ctll::anything, cls_push_rbracket, cls_items>;
	static constexpr auto rule(cls_first, minus__caret) -> ctll::push<ctll::anything, cls_push_char, cls_after_char>;
	static constexpr auto rule(cls_first, cls_char) -> ctll::push<ctll::anything, cls_push_char, cls_after_char>;
	static constexpr auto rule(cls_first, backslash) -> ctll::push<ctll::anything, cls_escape>;

	static constexpr auto rule(cls_first_pos, rbracket) -> ctll::push<ctll::anything, cls_push_rbracket, cls_items>;
	static constexpr auto rule(cls_first_pos, minus) -> ctll::push<ctll::anything, cls_push_char, cls_after_char>;
	static constexpr auto rule(cls_first_pos, cls_char) -> ctll::push<ctll::anything, cls_push_char, cls_after_char>;
	static constexpr auto rule(cls_first_pos, backslash) -> ctll::push<ctll::anything, cls_escape>;

	static constexpr auto rule(cls_items, caret) -> ctll::push<ctll::anything, cls_push_char, cls_after_char>;
	static constexpr auto rule(cls_items, cls_char) -> ctll::push<ctll::anything, cls_push_char, cls_after_char>;
	static constexpr auto rule(cls_items, backslash) -> ctll::push<ctll::anything, cls_escape>;
	static constexpr auto rule(cls_items, rbracket) -> ctll::push<ctll::anything, close_class, rx_atoms>;

	static constexpr auto rule(cls_after_char, minus) -> ctll::push<ctll::anything, cls_range_end>;
	static constexpr auto rule(cls_after_char, backslash__sclose__caret) -> ctll::push<cls_items>;
	static constexpr auto rule(cls_after_char, cls_char) -> ctll::push<cls_items>;

	static constexpr auto rule(cls_range_end, caret) -> ctll::push<ctll::anything, cls_make_range, cls_after_range>;
	static constexpr auto rule(cls_range_end, cls_char) -> ctll::push<ctll::anything, cls_make_range, cls_after_range>;
	static constexpr auto rule(cls_range_end, backslash) -> ctll::push<ctll::anything, cls_range_escape>;
	static constexpr auto rule(cls_range_end, rbracket) -> ctll::push<ctll::anything, cls_push_minus, close_class, rx_atoms>;

	static constexpr auto rule(cls_after_range, backslash__sclose__caret) -> ctll::push<cls_items>;
	static constexpr auto rule(cls_after_range, cls_char) -> ctll::push<cls_items>;

	static constexpr auto rule(cls_escape, f__n__r__t) -> ctll::push<ctll::anything, cls_esc_code, cls_after_char>;
	static constexpr auto rule(cls_escape, w) -> ctll::push<ctll::anything, cls_class_word, cls_items>;
	static constexpr auto rule(cls_escape, d) -> ctll::push<ctll::anything, cls_class_digit, cls_items>;
	static constexpr auto rule(cls_escape, s) -> ctll::push<ctll::anything, cls_class_space, cls_items>;
	static constexpr auto rule(cls_escape, W) -> ctll::push<ctll::anything, cls_class_not_word, cls_items>;
	static constexpr auto rule(cls_escape, D) -> ctll::push<ctll::anything, cls_class_not_digit, cls_items>;
	static constexpr auto rule(cls_escape, S) -> ctll::push<ctll::anything, cls_class_not_space, cls_items>;
	static constexpr auto rule(cls_escape, x) -> ctll::push<ctll::anything, hexdig, push_hex_high, hexdig, cls_hex_char, cls_after_char>;
	static constexpr auto rule(cls_escape, set_21) -> ctll::push<ctll::anything, cls_esc_char, cls_after_char>;

	static constexpr auto rule(cls_range_escape, f__n__r__t) -> ctll::push<ctll::anything, cls_range_esc_code, cls_after_range>;
	static constexpr auto rule(cls_range_escape, x) -> ctll::push<ctll::anything, hexdig, push_hex_high, hexdig, cls_range_hex_char, cls_after_range>;
	static constexpr auto rule(cls_range_escape, minus__sopen__backslash__sclose__caret) -> ctll::push<ctll::anything, cls_range_esc_char, cls_after_range>;

	static constexpr auto rule(statement, i) -> ctll::push<ctll::anything, statement_i>;

	static constexpr auto rule(statement_i, g) -> ctll::push<ctll::anything, n, o, r, e, mark_ignore, new_branch, ws, exp_atoms>;
	static constexpr auto rule(statement_i, m) -> ctll::push<ctll::anything, p, o, r, t, mark_import, ws1, import_path>;

	static constexpr auto rule(ws1, inline_ws) -> ctll::push<ctll::anything, ws>;

	static constexpr auto rule(import_path, uscore) -> ctll::push<ctll::anything, begin_name, push_name_char, import_seg_run>;
	static constexpr auto rule(import_path, set_4) -> ctll::push<ctll::anything, begin_name, push_name_char, import_seg_lc>;
	static constexpr auto rule(import_path, set_5) -> ctll::push<ctll::anything, begin_name, push_name_char, import_seg_uc>;

	static constexpr auto rule(import_seg_run, uscore) -> ctll::push<ctll::anything, push_name_char, import_seg_run>;
	static constexpr auto rule(import_seg_run, set_4) -> ctll::push<ctll::anything, push_name_char, import_seg_lc>;
	static constexpr auto rule(import_seg_run, set_5) -> ctll::push<ctll::anything, push_name_char, import_seg_uc>;

	static constexpr auto rule(import_seg_lc, set_7) -> ctll::push<ctll::anything, push_name_char, import_seg_lc>;
	static constexpr auto rule(import_seg_lc, set_22) -> ctll::push<import_seg, import_post>;
	static constexpr auto rule(import_seg_lc, ctll::epsilon) -> ctll::push<import_seg, import_post>;

	static constexpr auto rule(import_seg_uc, set_8) -> ctll::push<ctll::anything, push_name_char, import_seg_uc>;
	static constexpr auto rule(import_seg_uc, set_23) -> ctll::push<import_seg, import_post>;
	static constexpr auto rule(import_seg_uc, ctll::epsilon) -> ctll::push<import_seg, import_post>;

	static constexpr auto rule(import_post, dot) -> ctll::push<ctll::anything, import_path>;
	static constexpr auto rule(import_post, inline_ws) -> ctll::push<ctll::anything, import_post2>;
	static constexpr auto rule(import_post, newline) -> ctll::push<ctll::anything, skip>;
	static constexpr auto rule(import_post, slash) -> ctll::push<ctll::anything, slash, comment_tail>;
	static constexpr auto rule(import_post, set_2) -> ctll::epsilon;
	static constexpr auto rule(import_post, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(import_post2, inline_ws) -> ctll::push<ctll::anything, import_post2>;
	static constexpr auto rule(import_post2, minus) -> ctll::push<ctll::anything, gt, ws, import_alias_name>;
	static constexpr auto rule(import_post2, lparen) -> ctll::push<ctll::anything, ws, import_list_name>;
	static constexpr auto rule(import_post2, newline) -> ctll::push<ctll::anything, skip>;
	static constexpr auto rule(import_post2, slash) -> ctll::push<ctll::anything, slash, comment_tail>;
	static constexpr auto rule(import_post2, set_2) -> ctll::epsilon;
	static constexpr auto rule(import_post2, ctll::epsilon) -> ctll::epsilon;

	static constexpr auto rule(import_alias_name, uscore) -> ctll::push<ctll::anything, begin_name, push_name_char, import_alias_run>;
	static constexpr auto rule(import_alias_name, set_4) -> ctll::push<ctll::anything, begin_name, push_name_char, import_alias_lc>;
	static constexpr auto rule(import_alias_name, set_5) -> ctll::push<ctll::anything, begin_name, push_name_char, import_alias_uc>;

	static constexpr auto rule(import_alias_run, uscore) -> ctll::push<ctll::anything, push_name_char, import_alias_run>;
	static constexpr auto rule(import_alias_run, set_4) -> ctll::push<ctll::anything, push_name_char, import_alias_lc>;
	static constexpr auto rule(import_alias_run, set_5) -> ctll::push<ctll::anything, push_name_char, import_alias_uc>;

	static constexpr auto rule(import_alias_lc, set_7) -> ctll::push<ctll::anything, push_name_char, import_alias_lc>;
	static constexpr auto rule(import_alias_lc, set_24) -> ctll::push<import_alias, line_end>;
	static constexpr auto rule(import_alias_lc, ctll::epsilon) -> ctll::push<import_alias, line_end>;

	static constexpr auto rule(import_alias_uc, set_8) -> ctll::push<ctll::anything, push_name_char, import_alias_uc>;
	static constexpr auto rule(import_alias_uc, set_25) -> ctll::push<import_alias, line_end>;
	static constexpr auto rule(import_alias_uc, ctll::epsilon) -> ctll::push<import_alias, line_end>;

	static constexpr auto rule(import_list_name, uscore) -> ctll::push<ctll::anything, begin_name, push_name_char, import_list_run>;
	static constexpr auto rule(import_list_name, set_4) -> ctll::push<ctll::anything, begin_name, push_name_char, import_list_lc>;
	static constexpr auto rule(import_list_name, set_5) -> ctll::push<ctll::anything, begin_name, push_name_char, import_list_uc>;

	static constexpr auto rule(import_list_run, uscore) -> ctll::push<ctll::anything, push_name_char, import_list_run>;
	static constexpr auto rule(import_list_run, set_4) -> ctll::push<ctll::anything, push_name_char, import_list_lc>;
	static constexpr auto rule(import_list_run, set_5) -> ctll::push<ctll::anything, push_name_char, import_list_uc>;

	static constexpr auto rule(import_list_lc, set_7) -> ctll::push<ctll::anything, push_name_char, import_list_lc>;
	static constexpr auto rule(import_list_lc, inline_ws__close__comma) -> ctll::push<import_list_add, import_list_post>;

	static constexpr auto rule(import_list_uc, set_8) -> ctll::push<ctll::anything, push_name_char, import_list_uc>;
	static constexpr auto rule(import_list_uc, inline_ws__close__comma) -> ctll::push<import_list_add, import_list_post>;

	static constexpr auto rule(import_list_post, inline_ws) -> ctll::push<ctll::anything, import_list_post>;
	static constexpr auto rule(import_list_post, comma) -> ctll::push<ctll::anything, ws, import_list_name>;
	static constexpr auto rule(import_list_post, rparen) -> ctll::push<ctll::anything, line_end>;

	static constexpr auto rule(line_end, inline_ws) -> ctll::push<ctll::anything, line_end>;
	static constexpr auto rule(line_end, newline) -> ctll::push<ctll::anything, skip>;
	static constexpr auto rule(line_end, slash) -> ctll::push<ctll::anything, slash, comment_tail>;
	static constexpr auto rule(line_end, set_2) -> ctll::epsilon;
	static constexpr auto rule(line_end, ctll::epsilon) -> ctll::epsilon;

};

}

#endif //CTLARK__LARK__HPP
